# Generated by Django 4.2.7 on 2023-11-14 01:04

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'alternativas',
            },
        ),
        migrations.CreateModel(
            name='Alternativas_x_pregunta',
            fields=[
                ('id_alternativa_x_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('id_alternativa', models.ForeignKey(db_column='id_alternativa', on_delete=django.db.models.deletion.DO_NOTHING, to='application.alternativas')),
            ],
            options={
                'db_table': 'alternativas_x_pregunta',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, default=None, null=True)),
                ('fecha_fin', models.DateField(blank=True, default=None, null=True)),
                ('autor', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'facultad',
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=300)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'temas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_alternativa',
            fields=[
                ('id_tipo_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_alternativa',
            },
        ),
        migrations.CreateModel(
            name='Tipo_encuesta',
            fields=[
                ('id_tipo_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_encuesta',
            },
        ),
        migrations.CreateModel(
            name='Preguntas_x_encuesta',
            fields=[
                ('id_pregunta_x_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('id_encuesta', models.ForeignKey(db_column='id_encuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='application.encuesta')),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='application.preguntas')),
            ],
            options={
                'db_table': 'preguntas_x_encuesta',
            },
        ),
        migrations.AddField(
            model_name='preguntas',
            name='id_tema',
            field=models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.DO_NOTHING, to='application.temas'),
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
                ('id_modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.DO_NOTHING, to='application.modulos')),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.DO_NOTHING, to='application.permisos')),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id_escuela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.DO_NOTHING, to='application.facultad')),
            ],
            options={
                'db_table': 'escuela',
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='id_tipo_encuesta',
            field=models.ForeignKey(db_column='id_tipo_encuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipo_encuesta'),
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('numero_intentos', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('id_alternativa_x_pregunta', models.ForeignKey(db_column='id_alternativa_x_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='application.alternativas_x_pregunta')),
                ('id_auth_user', models.ForeignKey(db_column='id_auth_user', on_delete=django.db.models.deletion.DO_NOTHING, to='application.authuser')),
            ],
            options={
                'db_table': 'detalle',
            },
        ),
        migrations.CreateModel(
            name='Datos_personales',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField(default=0)),
                ('sexo', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, default=None, null=True)),
                ('grado_instruccion', models.IntegerField(default=1)),
                ('ocupacion', models.CharField(max_length=20)),
                ('anio_ingreso', models.IntegerField(default=0)),
                ('direccion_actual', models.CharField(max_length=50)),
                ('numero_celular', models.IntegerField(default=0)),
                ('vive_con', models.CharField(max_length=20)),
                ('numero_de_hermanos', models.IntegerField(default=0)),
                ('apoderado', models.CharField(max_length=50)),
                ('numero_celular_apoderado', models.IntegerField(default=0)),
                ('beneficio', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('id_auth_user', models.ForeignKey(db_column='id_auth_user', on_delete=django.db.models.deletion.DO_NOTHING, to='application.authuser')),
                ('id_escuela', models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.DO_NOTHING, to='application.escuela')),
            ],
            options={
                'db_table': 'datos_personales',
            },
        ),
        migrations.AddField(
            model_name='authuser',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='application.perfil'),
        ),
        migrations.AddField(
            model_name='alternativas_x_pregunta',
            name='id_pregunta_x_encuesta',
            field=models.ForeignKey(db_column='id_pregunta_x_encuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='application.preguntas_x_encuesta'),
        ),
        migrations.AddField(
            model_name='alternativas',
            name='id_tipo_alternativa',
            field=models.ForeignKey(db_column='id_tipo_alternativa', on_delete=django.db.models.deletion.DO_NOTHING, to='application.tipo_alternativa'),
        ),
    ]
