# Generated by Django 4.2.7 on 2023-11-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='id_permiso',
        ),
        migrations.AddField(
            model_name='permisos',
            name='id_perfil',
            field=models.ForeignKey(db_column='id_perfil', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='application.perfil'),
        ),
    ]
